const mysqlMulin = require('../startup/dbMulin');
const {DataTypes} = require('sequelize');


const Concplant1 = mysqlMulin.define('concplant_1', {       //инициализация
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        sand_netto: {type: DataTypes.FLOAT},
        sand_set: {type: DataTypes.FLOAT},
        rub_netto: {type: DataTypes.FLOAT},
        rub_set: {type: DataTypes.FLOAT},
        keram_netto: {type: DataTypes.FLOAT},
        keram_set: {type: DataTypes.FLOAT},
        null_netto: {type: DataTypes.FLOAT},
        null_set: {type: DataTypes.FLOAT},
        cem1_netto: {type: DataTypes.FLOAT},
        cem1_set: {type: DataTypes.FLOAT},
        cem2_netto: {type: DataTypes.FLOAT},
        cem2_set: {type: DataTypes.FLOAT},
        cem3_netto: {type: DataTypes.FLOAT},
        cem3_set: {type: DataTypes.FLOAT},
        wat1_netto: {type: DataTypes.FLOAT},
        wat1_set: {type: DataTypes.FLOAT},
        wat2_netto: {type: DataTypes.FLOAT},
        wat2_set: {type: DataTypes.FLOAT},
        chem1_netto: {type: DataTypes.FLOAT},
        chem1_set: {type: DataTypes.FLOAT},
        chem2_netto: {type: DataTypes.FLOAT},
        chem2_set: {type: DataTypes.FLOAT},
        chem3_netto: {type: DataTypes.FLOAT},
        chem3_set: {type: DataTypes.FLOAT},
        mix_current: {type: DataTypes.FLOAT},
        cur_count: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        id_prog: {type: DataTypes.BIGINT},
        change_bunk_id: {type: DataTypes.BIGINT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Concplant2 = mysqlMulin.define('concplant_2', {       //инициализация
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        sand_netto: {type: DataTypes.FLOAT},
        sand_set: {type: DataTypes.FLOAT},
        rub_netto: {type: DataTypes.FLOAT},
        rub_set: {type: DataTypes.FLOAT},
        keram_netto: {type: DataTypes.FLOAT},
        keram_set: {type: DataTypes.FLOAT},
        null_netto: {type: DataTypes.FLOAT},
        null_set: {type: DataTypes.FLOAT},
        cem1_netto: {type: DataTypes.FLOAT},
        cem1_set: {type: DataTypes.FLOAT},
        cem2_netto: {type: DataTypes.FLOAT},
        cem2_set: {type: DataTypes.FLOAT},
        cem3_netto: {type: DataTypes.FLOAT},
        cem3_set: {type: DataTypes.FLOAT},
        wat1_netto: {type: DataTypes.FLOAT},
        wat1_set: {type: DataTypes.FLOAT},
        wat2_netto: {type: DataTypes.FLOAT},
        wat2_set: {type: DataTypes.FLOAT},
        chem1_netto: {type: DataTypes.FLOAT},
        chem1_set: {type: DataTypes.FLOAT},
        chem2_netto: {type: DataTypes.FLOAT},
        chem2_set: {type: DataTypes.FLOAT},
        chem3_netto: {type: DataTypes.FLOAT},
        chem3_set: {type: DataTypes.FLOAT},
        mix_current: {type: DataTypes.FLOAT},
        cur_count: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        id_prog: {type: DataTypes.BIGINT},
        change_bunk_id: {type: DataTypes.BIGINT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Concplant3 = mysqlMulin.define('concplant_3', {       //инициализация
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        sand_netto: {type: DataTypes.FLOAT},
        sand_set: {type: DataTypes.FLOAT},
        rub_netto: {type: DataTypes.FLOAT},
        rub_set: {type: DataTypes.FLOAT},
        keram_netto: {type: DataTypes.FLOAT},
        keram_set: {type: DataTypes.FLOAT},
        null_netto: {type: DataTypes.FLOAT},
        null_set: {type: DataTypes.FLOAT},
        cem1_netto: {type: DataTypes.FLOAT},
        cem1_set: {type: DataTypes.FLOAT},
        cem2_netto: {type: DataTypes.FLOAT},
        cem2_set: {type: DataTypes.FLOAT},
        cem3_netto: {type: DataTypes.FLOAT},
        cem3_set: {type: DataTypes.FLOAT},
        wat1_netto: {type: DataTypes.FLOAT},
        wat1_set: {type: DataTypes.FLOAT},
        wat2_netto: {type: DataTypes.FLOAT},
        wat2_set: {type: DataTypes.FLOAT},
        chem1_netto: {type: DataTypes.FLOAT},
        chem1_set: {type: DataTypes.FLOAT},
        chem2_netto: {type: DataTypes.FLOAT},
        chem2_set: {type: DataTypes.FLOAT},
        chem3_netto: {type: DataTypes.FLOAT},
        chem3_set: {type: DataTypes.FLOAT},
        mix_current: {type: DataTypes.FLOAT},
        cur_count: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        id_prog: {type: DataTypes.BIGINT},
        change_bunk_id: {type: DataTypes.BIGINT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Concplant4 = mysqlMulin.define('concplant_4', {       //инициализация
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        sand_netto: {type: DataTypes.FLOAT},
        sand_set: {type: DataTypes.FLOAT},
        rub_netto: {type: DataTypes.FLOAT},
        rub_set: {type: DataTypes.FLOAT},
        keram_netto: {type: DataTypes.FLOAT},
        keram_set: {type: DataTypes.FLOAT},
        null_netto: {type: DataTypes.FLOAT},
        null_set: {type: DataTypes.FLOAT},
        cem1_netto: {type: DataTypes.FLOAT},
        cem1_set: {type: DataTypes.FLOAT},
        cem2_netto: {type: DataTypes.FLOAT},
        cem2_set: {type: DataTypes.FLOAT},
        cem3_netto: {type: DataTypes.FLOAT},
        cem3_set: {type: DataTypes.FLOAT},
        wat1_netto: {type: DataTypes.FLOAT},
        wat1_set: {type: DataTypes.FLOAT},
        wat2_netto: {type: DataTypes.FLOAT},
        wat2_set: {type: DataTypes.FLOAT},
        chem1_netto: {type: DataTypes.FLOAT},
        chem1_set: {type: DataTypes.FLOAT},
        chem2_netto: {type: DataTypes.FLOAT},
        chem2_set: {type: DataTypes.FLOAT},
        chem3_netto: {type: DataTypes.FLOAT},
        chem3_set: {type: DataTypes.FLOAT},
        mix_current: {type: DataTypes.FLOAT},
        cur_count: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        id_prog: {type: DataTypes.BIGINT},
        change_bunk_id: {type: DataTypes.BIGINT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Concplant5 = mysqlMulin.define('concplant_5', {       //инициализация
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        sand_netto: {type: DataTypes.FLOAT},
        sand_set: {type: DataTypes.FLOAT},
        rub_netto: {type: DataTypes.FLOAT},
        rub_set: {type: DataTypes.FLOAT},
        keram_netto: {type: DataTypes.FLOAT},
        keram_set: {type: DataTypes.FLOAT},
        null_netto: {type: DataTypes.FLOAT},
        null_set: {type: DataTypes.FLOAT},
        cem1_netto: {type: DataTypes.FLOAT},
        cem1_set: {type: DataTypes.FLOAT},
        cem2_netto: {type: DataTypes.FLOAT},
        cem2_set: {type: DataTypes.FLOAT},
        cem3_netto: {type: DataTypes.FLOAT},
        cem3_set: {type: DataTypes.FLOAT},
        wat1_netto: {type: DataTypes.FLOAT},
        wat1_set: {type: DataTypes.FLOAT},
        wat2_netto: {type: DataTypes.FLOAT},
        wat2_set: {type: DataTypes.FLOAT},
        chem1_netto: {type: DataTypes.FLOAT},
        chem1_set: {type: DataTypes.FLOAT},
        chem2_netto: {type: DataTypes.FLOAT},
        chem2_set: {type: DataTypes.FLOAT},
        chem3_netto: {type: DataTypes.FLOAT},
        chem3_set: {type: DataTypes.FLOAT},
        mix_current: {type: DataTypes.FLOAT},
        cur_count: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        id_prog: {type: DataTypes.BIGINT},
        change_bunk_id: {type: DataTypes.BIGINT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Programs1 = mysqlMulin.define('programs_1', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        id_prog: {type: DataTypes.BIGINT, allowNull: false},
        client: {type: DataTypes.TEXT},
        car: {type: DataTypes.TEXT},
        drivename: {type: DataTypes.TEXT},
        shipper: {type: DataTypes.TEXT},
        perevoz: {type: DataTypes.TEXT},
        produc: {type: DataTypes.TEXT},
        rec_name: {type: DataTypes.TEXT},
        id_req_rec: {type: DataTypes.INTEGER},
        ttn: {type: DataTypes.INTEGER},
        m_list: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        volume: {type: DataTypes.FLOAT},
        rec_vol: {type: DataTypes.FLOAT},
        rec_sand: {type: DataTypes.FLOAT},
        rec_rub: {type: DataTypes.FLOAT},
        rec_keram: {type: DataTypes.FLOAT},
        rec_null: {type: DataTypes.FLOAT},
        rec_cem1: {type: DataTypes.FLOAT},
        rec_cem2: {type: DataTypes.FLOAT},
        rec_wat1: {type: DataTypes.FLOAT},
        rec_wat2: {type: DataTypes.FLOAT},
        rec_chem1: {type: DataTypes.FLOAT},
        rec_chem2: {type: DataTypes.FLOAT},
        rec_chem3: {type: DataTypes.FLOAT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Programs2 = mysqlMulin.define('programs_2', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        id_prog: {type: DataTypes.BIGINT, allowNull: false},
        client: {type: DataTypes.TEXT},
        car: {type: DataTypes.TEXT},
        drivename: {type: DataTypes.TEXT},
        shipper: {type: DataTypes.TEXT},
        perevoz: {type: DataTypes.TEXT},
        produc: {type: DataTypes.TEXT},
        rec_name: {type: DataTypes.TEXT},
        id_req_rec: {type: DataTypes.INTEGER},
        ttn: {type: DataTypes.INTEGER},
        m_list: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        volume: {type: DataTypes.FLOAT},
        rec_vol: {type: DataTypes.FLOAT},
        rec_sand: {type: DataTypes.FLOAT},
        rec_rub: {type: DataTypes.FLOAT},
        rec_keram: {type: DataTypes.FLOAT},
        rec_null: {type: DataTypes.FLOAT},
        rec_cem1: {type: DataTypes.FLOAT},
        rec_cem2: {type: DataTypes.FLOAT},
        rec_wat1: {type: DataTypes.FLOAT},
        rec_wat2: {type: DataTypes.FLOAT},
        rec_chem1: {type: DataTypes.FLOAT},
        rec_chem2: {type: DataTypes.FLOAT},
        rec_chem3: {type: DataTypes.FLOAT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Programs3 = mysqlMulin.define('programs_3', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        id_prog: {type: DataTypes.BIGINT, allowNull: false},
        client: {type: DataTypes.TEXT},
        car: {type: DataTypes.TEXT},
        drivename: {type: DataTypes.TEXT},
        shipper: {type: DataTypes.TEXT},
        perevoz: {type: DataTypes.TEXT},
        produc: {type: DataTypes.TEXT},
        rec_name: {type: DataTypes.TEXT},
        id_req_rec: {type: DataTypes.INTEGER},
        ttn: {type: DataTypes.INTEGER},
        m_list: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        volume: {type: DataTypes.FLOAT},
        rec_vol: {type: DataTypes.FLOAT},
        rec_sand: {type: DataTypes.FLOAT},
        rec_rub: {type: DataTypes.FLOAT},
        rec_keram: {type: DataTypes.FLOAT},
        rec_null: {type: DataTypes.FLOAT},
        rec_cem1: {type: DataTypes.FLOAT},
        rec_cem2: {type: DataTypes.FLOAT},
        rec_wat1: {type: DataTypes.FLOAT},
        rec_wat2: {type: DataTypes.FLOAT},
        rec_chem1: {type: DataTypes.FLOAT},
        rec_chem2: {type: DataTypes.FLOAT},
        rec_chem3: {type: DataTypes.FLOAT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Programs4 = mysqlMulin.define('programs_4', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        id_prog: {type: DataTypes.BIGINT, allowNull: false},
        client: {type: DataTypes.TEXT},
        car: {type: DataTypes.TEXT},
        drivename: {type: DataTypes.TEXT},
        shipper: {type: DataTypes.TEXT},
        perevoz: {type: DataTypes.TEXT},
        produc: {type: DataTypes.TEXT},
        rec_name: {type: DataTypes.TEXT},
        id_req_rec: {type: DataTypes.INTEGER},
        ttn: {type: DataTypes.INTEGER},
        m_list: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        volume: {type: DataTypes.FLOAT},
        rec_vol: {type: DataTypes.FLOAT},
        rec_sand: {type: DataTypes.FLOAT},
        rec_rub: {type: DataTypes.FLOAT},
        rec_keram: {type: DataTypes.FLOAT},
        rec_null: {type: DataTypes.FLOAT},
        rec_cem1: {type: DataTypes.FLOAT},
        rec_cem2: {type: DataTypes.FLOAT},
        rec_wat1: {type: DataTypes.FLOAT},
        rec_wat2: {type: DataTypes.FLOAT},
        rec_chem1: {type: DataTypes.FLOAT},
        rec_chem2: {type: DataTypes.FLOAT},
        rec_chem3: {type: DataTypes.FLOAT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Programs5 = mysqlMulin.define('programs_5', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        id_prog: {type: DataTypes.BIGINT, allowNull: false},
        client: {type: DataTypes.TEXT},
        car: {type: DataTypes.TEXT},
        drivename: {type: DataTypes.TEXT},
        shipper: {type: DataTypes.TEXT},
        perevoz: {type: DataTypes.TEXT},
        produc: {type: DataTypes.TEXT},
        rec_name: {type: DataTypes.TEXT},
        id_req_rec: {type: DataTypes.INTEGER},
        ttn: {type: DataTypes.INTEGER},
        m_list: {type: DataTypes.INTEGER},
        all_count: {type: DataTypes.INTEGER},
        volume: {type: DataTypes.FLOAT},
        rec_vol: {type: DataTypes.FLOAT},
        rec_sand: {type: DataTypes.FLOAT},
        rec_rub: {type: DataTypes.FLOAT},
        rec_keram: {type: DataTypes.FLOAT},
        rec_null: {type: DataTypes.FLOAT},
        rec_cem1: {type: DataTypes.FLOAT},
        rec_cem2: {type: DataTypes.FLOAT},
        rec_wat1: {type: DataTypes.FLOAT},
        rec_wat2: {type: DataTypes.FLOAT},
        rec_chem1: {type: DataTypes.FLOAT},
        rec_chem2: {type: DataTypes.FLOAT},
        rec_chem3: {type: DataTypes.FLOAT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const ChangeMaterial1 = mysqlMulin.define('change_material_1', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        bunk1_mat_id: {type: DataTypes.INTEGER},
        bunk2_mat_id: {type: DataTypes.INTEGER},
        bunk3_mat_id: {type: DataTypes.INTEGER},
        bunk4_mat_id: {type: DataTypes.INTEGER},
        cem1_mat_id: {type: DataTypes.INTEGER},
        cem2_mat_id: {type: DataTypes.INTEGER},
        cem3_mat_id: {type: DataTypes.INTEGER},
        chem1_mat_id: {type: DataTypes.INTEGER},
        chem2_mat_id: {type: DataTypes.INTEGER},
        chem3_mat_id: {type: DataTypes.INTEGER},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const ChangeMaterial2 = mysqlMulin.define('change_material_2', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        bunk1_mat_id: {type: DataTypes.INTEGER},
        bunk2_mat_id: {type: DataTypes.INTEGER},
        bunk3_mat_id: {type: DataTypes.INTEGER},
        bunk4_mat_id: {type: DataTypes.INTEGER},
        cem1_mat_id: {type: DataTypes.INTEGER},
        cem2_mat_id: {type: DataTypes.INTEGER},
        cem3_mat_id: {type: DataTypes.INTEGER},
        chem1_mat_id: {type: DataTypes.INTEGER},
        chem2_mat_id: {type: DataTypes.INTEGER},
        chem3_mat_id: {type: DataTypes.INTEGER},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const ChangeMaterial3 = mysqlMulin.define('change_material_3', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        bunk1_mat_id: {type: DataTypes.INTEGER},
        bunk2_mat_id: {type: DataTypes.INTEGER},
        bunk3_mat_id: {type: DataTypes.INTEGER},
        bunk4_mat_id: {type: DataTypes.INTEGER},
        cem1_mat_id: {type: DataTypes.INTEGER},
        cem2_mat_id: {type: DataTypes.INTEGER},
        cem3_mat_id: {type: DataTypes.INTEGER},
        chem1_mat_id: {type: DataTypes.INTEGER},
        chem2_mat_id: {type: DataTypes.INTEGER},
        chem3_mat_id: {type: DataTypes.INTEGER},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const ChangeMaterial4 = mysqlMulin.define('change_material_4', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        bunk1_mat_id: {type: DataTypes.INTEGER},
        bunk2_mat_id: {type: DataTypes.INTEGER},
        bunk3_mat_id: {type: DataTypes.INTEGER},
        bunk4_mat_id: {type: DataTypes.INTEGER},
        cem1_mat_id: {type: DataTypes.INTEGER},
        cem2_mat_id: {type: DataTypes.INTEGER},
        cem3_mat_id: {type: DataTypes.INTEGER},
        chem1_mat_id: {type: DataTypes.INTEGER},
        chem2_mat_id: {type: DataTypes.INTEGER},
        chem3_mat_id: {type: DataTypes.INTEGER},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const ChangeMaterial5 = mysqlMulin.define('change_material_5', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        bunk1_mat_id: {type: DataTypes.INTEGER},
        bunk2_mat_id: {type: DataTypes.INTEGER},
        bunk3_mat_id: {type: DataTypes.INTEGER},
        bunk4_mat_id: {type: DataTypes.INTEGER},
        cem1_mat_id: {type: DataTypes.INTEGER},
        cem2_mat_id: {type: DataTypes.INTEGER},
        cem3_mat_id: {type: DataTypes.INTEGER},
        chem1_mat_id: {type: DataTypes.INTEGER},
        chem2_mat_id: {type: DataTypes.INTEGER},
        chem3_mat_id: {type: DataTypes.INTEGER},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LevelMaterial1 = mysqlMulin.define('level_material_1', {
        id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
        id_master: {type: DataTypes.BIGINT, allowNull: false},
        sand: {type: DataTypes.FLOAT},
        rub: {type: DataTypes.FLOAT},
        keram: {type: DataTypes.FLOAT},
        _null: {type: DataTypes.FLOAT},
        cem1: {type: DataTypes.FLOAT},
        cem2: {type: DataTypes.FLOAT},
        cem3: {type: DataTypes.FLOAT},
        chem1: {type: DataTypes.FLOAT},
        chem2: {type: DataTypes.FLOAT},
        chem3: {type: DataTypes.FLOAT},
        created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LevelMaterial2 = mysqlMulin.define('level_material_2', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            sand: {type: DataTypes.FLOAT},
            rub: {type: DataTypes.FLOAT},
            keram: {type: DataTypes.FLOAT},
            _null: {type: DataTypes.FLOAT},
            cem1: {type: DataTypes.FLOAT},
            cem2: {type: DataTypes.FLOAT},
            cem3: {type: DataTypes.FLOAT},
            chem1: {type: DataTypes.FLOAT},
            chem2: {type: DataTypes.FLOAT},
            chem3: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LevelMaterial3 = mysqlMulin.define('level_material_3', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            sand: {type: DataTypes.FLOAT},
            rub: {type: DataTypes.FLOAT},
            keram: {type: DataTypes.FLOAT},
            _null: {type: DataTypes.FLOAT},
            cem1: {type: DataTypes.FLOAT},
            cem2: {type: DataTypes.FLOAT},
            cem3: {type: DataTypes.FLOAT},
            chem1: {type: DataTypes.FLOAT},
            chem2: {type: DataTypes.FLOAT},
            chem3: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LevelMaterial4 = mysqlMulin.define('level_material_4', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            sand: {type: DataTypes.FLOAT},
            rub: {type: DataTypes.FLOAT},
            keram: {type: DataTypes.FLOAT},
            _null: {type: DataTypes.FLOAT},
            cem1: {type: DataTypes.FLOAT},
            cem2: {type: DataTypes.FLOAT},
            cem3: {type: DataTypes.FLOAT},
            chem1: {type: DataTypes.FLOAT},
            chem2: {type: DataTypes.FLOAT},
            chem3: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LevelMaterial5 = mysqlMulin.define('level_material_5', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            sand: {type: DataTypes.FLOAT},
            rub: {type: DataTypes.FLOAT},
            keram: {type: DataTypes.FLOAT},
            _null: {type: DataTypes.FLOAT},
            cem1: {type: DataTypes.FLOAT},
            cem2: {type: DataTypes.FLOAT},
            cem3: {type: DataTypes.FLOAT},
            chem1: {type: DataTypes.FLOAT},
            chem2: {type: DataTypes.FLOAT},
            chem3: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogException1 = mysqlMulin.define('logs_exception_1', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name_function: {type: DataTypes.TEXT},
            exception: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogException2 = mysqlMulin.define('logs_exception_2', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name_function: {type: DataTypes.TEXT},
            exception: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogException3 = mysqlMulin.define('logs_exception_3', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name_function: {type: DataTypes.TEXT},
            exception: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogException4 = mysqlMulin.define('logs_exception_4', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name_function: {type: DataTypes.TEXT},
            exception: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogsException5 = mysqlMulin.define('logs_exception_5', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name_function: {type: DataTypes.TEXT},
            exception: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogMaterial1 = mysqlMulin.define('logs_materials_1', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            set_add: {type: DataTypes.INTEGER},
            level_silo_old: {type: DataTypes.FLOAT},
            level_silo_new: {type: DataTypes.FLOAT},
            zero_value: {type: DataTypes.FLOAT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogMaterial2 = mysqlMulin.define('logs_materials_2', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            set_add: {type: DataTypes.INTEGER},
            level_silo_old: {type: DataTypes.FLOAT},
            level_silo_new: {type: DataTypes.FLOAT},
            zero_value: {type: DataTypes.FLOAT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogMaterial3 = mysqlMulin.define('logs_materials_3', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            set_add: {type: DataTypes.INTEGER},
            level_silo_old: {type: DataTypes.FLOAT},
            level_silo_new: {type: DataTypes.FLOAT},
            zero_value: {type: DataTypes.FLOAT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogMaterial4 = mysqlMulin.define('logs_materials_4', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            set_add: {type: DataTypes.INTEGER},
            level_silo_old: {type: DataTypes.FLOAT},
            level_silo_new: {type: DataTypes.FLOAT},
            zero_value: {type: DataTypes.FLOAT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const LogMaterial5 = mysqlMulin.define('logs_materials_5', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            set_add: {type: DataTypes.INTEGER},
            level_silo_old: {type: DataTypes.FLOAT},
            level_silo_new: {type: DataTypes.FLOAT},
            zero_value: {type: DataTypes.FLOAT},
            comment: {type: DataTypes.TEXT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Materials1 = mysqlMulin.define('materials_1', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            visible: {type: DataTypes.INTEGER},
            not_inert: {type: DataTypes.INTEGER},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Materials2 = mysqlMulin.define('materials_2', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            visible: {type: DataTypes.INTEGER},
            not_inert: {type: DataTypes.INTEGER},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Materials3 = mysqlMulin.define('materials_3', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            visible: {type: DataTypes.INTEGER},
            not_inert: {type: DataTypes.INTEGER},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Materials4 = mysqlMulin.define('materials_4', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            visible: {type: DataTypes.INTEGER},
            not_inert: {type: DataTypes.INTEGER},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const Materials5 = mysqlMulin.define('materials_5', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            name: {type: DataTypes.TEXT},
            comment: {type: DataTypes.TEXT},
            visible: {type: DataTypes.INTEGER},
            not_inert: {type: DataTypes.INTEGER},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const StoreLevel1 = mysqlMulin.define('store_level_1', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            id_material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            old_value: {type: DataTypes.FLOAT},
            sub_value: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const StoreLevel2 = mysqlMulin.define('store_level_2', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            id_material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            old_value: {type: DataTypes.FLOAT},
            sub_value: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const StoreLevel3 = mysqlMulin.define('store_level_3', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            id_material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            old_value: {type: DataTypes.FLOAT},
            sub_value: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const StoreLevel4 = mysqlMulin.define('store_level_4', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            id_material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            old_value: {type: DataTypes.FLOAT},
            sub_value: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})

const StoreLevel5 = mysqlMulin.define('store_level_5', {
            id: {type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true},
            id_master: {type: DataTypes.BIGINT, allowNull: false},
            id_material: {type: DataTypes.INTEGER},
            value: {type: DataTypes.FLOAT},
            old_value: {type: DataTypes.FLOAT},
            sub_value: {type: DataTypes.FLOAT},
            created_at: {type: DataTypes.DATE},
    },
    {freezeTableName: true})










module.exports = {
    Concplant1,
    Concplant2,
    Concplant3,
    Concplant4,
    Concplant5,

}